# Generated by Django 5.2.7 on 2025-11-03 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLogro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('primer_gasto', 'Primer Gasto'), ('primer_ingreso', 'Primer Ingreso'), ('gasto_mensual', 'Gasto Mensual'), ('ahorro_mensual', 'Ahorro Mensual'), ('consistencia', 'Consistencia'), ('meta_ahorro', 'Meta de Ahorro')], max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='trophy', max_length=100)),
                ('color', models.CharField(default='#4f46e5', max_length=50)),
                ('meta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Logro',
                'verbose_name_plural': 'Tipos de Logros',
                'db_table': 'tipos_logros',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gasto_alto', 'Gasto Alto'), ('presupuesto_excedido', 'Presupuesto Excedido'), ('meta_cercana', 'Meta Cercana'), ('ingreso_irregular', 'Ingreso Irregular'), ('consejo_ahorro', 'Consejo de Ahorro')], max_length=50)),
                ('nivel', models.CharField(choices=[('info', 'Información'), ('advertencia', 'Advertencia'), ('urgente', 'Urgente')], default='info', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('datos_adicionales', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alertas',
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_logro', models.CharField(choices=[('primer_gasto', 'Primer Gasto'), ('primer_ingreso', 'Primer Ingreso'), ('meta_completada', 'Meta Completada'), ('consistencia_semanal', 'Consistencia Semanal'), ('ahorro_mensual', 'Ahorro Mensual'), ('control_gastos', 'Control de Gastos')], max_length=50)),
                ('mensaje', models.TextField()),
                ('icono', models.CharField(default='🏆', max_length=20)),
                ('fecha_obtenido', models.DateTimeField(auto_now_add=True)),
                ('visto', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'db_table': 'logros',
            },
        ),
        migrations.CreateModel(
            name='MetaAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_meta', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('meta_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('icono', models.CharField(choices=[('🏠', 'Casa'), ('🚗', 'Auto'), ('✈️', 'Viaje'), ('🎓', 'Educación'), ('💍', 'Boda'), ('🎁', 'Regalo'), ('💼', 'Negocio'), ('🏥', 'Salud'), ('🎯', 'Objetivo'), ('💰', 'Dinero')], default='🎯', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_objetivo', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('completada', 'Completada'), ('vencida', 'Vencida')], default='activa', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta de Ahorro',
                'verbose_name_plural': 'Metas de Ahorro',
                'db_table': 'metas',
            },
        ),
        migrations.CreateModel(
            name='ResumenHabitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.CharField(max_length=10)),
                ('total_dias', models.IntegerField(default=0)),
                ('dias_con_registros', models.IntegerField(default=0)),
                ('tasa_consistencia', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resumen de Hábitos',
                'verbose_name_plural': 'Resúmenes de Hábitos',
                'db_table': 'resumen_habitos',
            },
        ),
        migrations.CreateModel(
            name='HabitoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('gasto', 'Gasto'), ('ingreso', 'Ingreso')], max_length=20)),
                ('registrado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habitos_financieros',
                'unique_together': {('usuario', 'fecha', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='LogroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to=settings.AUTH_USER_MODEL)),
                ('tipo_logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.tipologro')),
            ],
            options={
                'db_table': 'logros_usuarios',
                'unique_together': {('usuario', 'tipo_logro')},
            },
        ),
    ]
