# Generated by Django 5.2.7 on 2025-11-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_alter_alerta_options_alter_logro_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitofinanciero',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='habitofinanciero',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='logro',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='resumenhabitos',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='metaahorro',
            options={'verbose_name': 'Meta de Ahorro', 'verbose_name_plural': 'Metas de Ahorro'},
        ),
        migrations.AlterModelOptions(
            name='tipologro',
            options={'verbose_name': 'Tipo de Logro', 'verbose_name_plural': 'Tipos de Logros'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Alerta',
        ),
        migrations.DeleteModel(
            name='HabitoFinanciero',
        ),
        migrations.DeleteModel(
            name='Logro',
        ),
        migrations.DeleteModel(
            name='ResumenHabitos',
        ),
    ]
